---
title: 2018 SACNAS Poster Figures
author: Juan M Vazquez
date: '2018-10-04'
slug: 2018-sacnas-poster-figures
categories:
  - DataInMotion
  - Conference
tags:
  - PetosParadox
  - plot
header:
  caption: ''
  image: ''
bibliography: "../../../RecBlast/data/bib/2018SACNAS-noSEER.bib"
biblio-style: apalike
output:
  blogdown::html_page:
    pre_knit: |+ 
      function(input, ...) {
      require(workflowr)
      add_bibliography <- function(sessioninfo, lines) {
      stopifnot(is.character(sessioninfo), is.character(lines))
      if (!any(stringr::str_detect(lines, '<div id=[\\\'\\\"]refs[\\\'\\\"]>'))) {
        sessioninfo <- c('', '<div id=\\\"refs\\\"></div>', '', sessioninfo)
      }
      return(sessioninfo)
      }
      frames <- sys.frames()
      e <- frames[[length(frames) - 2]]
      lines_in <- readLines(input)
      tmpfile <- file.path(tempdir(), basename(input))
      e$knit_input <- tmpfile
      wflow_opts <- workflowr:::wflow_options(input)
      header <- rmarkdown::yaml_front_matter(input)
      header_opts <- header$workflowr
      for (opt in names(header_opts)) {
      wflow_opts[[opt]] <- header_opts[[opt]]
      }
      if (!is.null(wflow_opts$knit_root_dir)) {
      if (!R.utils::isAbsolutePath(wflow_opts$knit_root_dir)) {
      wflow_opts$knit_root_dir <- workflowr:::absolute(file.path(dirname(input),
      wflow_opts$knit_root_dir))
      }
      }
      if (is.null(wflow_opts$knit_root_dir)) {
      wflow_opts$knit_root_dir <- dirname(workflowr:::absolute(input))
      }
      if (is.null(e$knit_root_dir)) {
      e$knit_root_dir <- wflow_opts$knit_root_dir
      } else {
      wflow_opts$knit_root_dir <- e$knit_root_dir
      }
      header_delims <- stringr::str_which(lines_in, '^-{3}|^\\\\.{3}')
      if (length(header_delims) >= 2) {
      header_end <- header_delims[2]
      header_lines <- lines_in[seq(header_end)]
      } else {
      header_end <- 0
      header_lines <- NULL
      }
      output_dir <- workflowr:::get_output_dir(directory = dirname(input))
      has_code <- workflowr:::detect_code(input)
      report <- workflowr:::create_report(input, output_dir, has_code, wflow_opts)
      if (has_code && is.numeric(wflow_opts$seed) && length(wflow_opts$seed) == 1) {
      seed_chunk <- c('',
      '```{r seed-set-by-workflowr, echo = FALSE}',
      sprintf('set.seed(%d)', wflow_opts$seed),
      '```',
      '')
      } else {
      seed_chunk <- ''
      }
      if (has_code && wflow_opts$sessioninfo != '') {
      sessioninfo <- c('',
      '## Session information',
      '',
      '```{r session-info-chunk-inserted-by-workflowr}',
      wflow_opts$sessioninfo,
      '```',
      '')
      if (!is.null(header$bibliography)) {
      sessioninfo <- add_bibliography(sessioninfo, lines_in)
      }
      } else {
      sessioninfo <- ''
      }
      lines_out <- c(header_lines,
      '**Last updated:** `r Sys.Date()`',
      report,
      '---',
      seed_chunk,
      lines_in[(header_end + 1):length(lines_in)],
      sessioninfo)
      writeLines(lines_out, tmpfile)
      }
---

## Introduction

```{r, eval=T}
# Libraries
library(ggtree)
library(ggimage)
library(ggpubr)
library(ggstance)
library(tidyverse)
options(readr.num_columns = 0)
library(magrittr)
library(RColorBrewer)
library(viridis)
library(wordcloud)
```

```{r Tree, eval-F, eval=T}
# Color Scheme for Afrotheria
afrotheria.clades <- c("Afroinsectivora", "Xenarthra", "Pseudoungulata","Paenungulata", "Tethytheria", "Elephantidae")
afrotheria.cladesPlusOne <- c("Other", "Afroinsectivora", "Xenarthra", "Pseudoungulata","Paenungulata", "Tethytheria", "Elephantidae")
afrotheria.colorScheme <- brewer.pal(length(afrotheria.cladesPlusOne), name = "Dark2")
#names(afrotheria.colorScheme) <- afrotheria.cladesPlusOne  # Kills the whole thing
afrotheria.colorScheme.species <- list(
  "Loxodonta africana" = "#A6761D",
  "Loxodonta cyclotis" = "#976C1B",
  "Mammuthus primigenius" = "#886118",
  "Mammuthus columbi" = "#795616",
  "Elephas maximus" = "#5B4110",
  "Mammut americanum" = "#3D2B0B",
  "Trichechus manatus" = "#E6AB02",
  "Procavia capensis" = "#66A61E",
  "Orycteropus afer" = "#E7298A",
  "Echinops telfairi" = "#7570B3",
  "Chrysochloris asiatica" = "#605C93",
  "Elephantulus edwardii" = "#4B4872",
  "Choloepus hoffmanni" = "#D95F02",
  "Dasypus novemcinctus" = "#C65702"
)

# Data
afrotreeria <- read.newick("../../../RecBlast/data/tree/afrotheria.tree")
afrotreeria$tip.label %<>% gsub("_"," ", .)
afrotheria.lifesize <- read.delim("../../../RecBlast/data/other/anage_data.txt", stringsAsFactors = FALSE) %>% 
  as.tibble() %>% 
  unite(SciName, c("Genus", "Species"), sep=" ", remove=F) %>% 
  filter(SciName %in% afrotreeria$tip.label) %>% 
  select(SciName, Family, Genus, Species, Maximum.longevity..yrs., Adult.weight..g.) %>%
  dplyr::rename(id=SciName)
afrotheria.lifesize %<>% full_join(tibble(id=afrotreeria$tip.label), ., by="id")
afrotheria.lifesize$Family[1:6] <- rep("Elephantidae", 6)
afrotheria.lifesize$Genus[1] <- "Loxodonta"
afrotheria.lifesize$Genus[3:4] <- rep("Mammuthus",2)
afrotheria.lifesize$Genus[6] <- "Mammut"
afrotheria.lifesize$Species[1] <- "cyclotis"
afrotheria.lifesize$Species[3] <- "columbi"
afrotheria.lifesize$Species[4] <- "primigenius"
afrotheria.lifesize$Species[6] <- "americanum"
afrotheria.lifesize$Adult.weight..g.[10] <- 47  #https://animaldiversity.org/accounts/Chrysochloris_asiatica/
afrotheria.lifesize$Adult.weight..g.[1] <- 2.7e+6  # http://www.arkive.org/forest-elephant/loxodonta-cyclotis/#text=Facts ; Spinage, C. (1994) Elephants. T. & A. D. Poyser Ltd, London.
afrotheria.lifesize$Adult.weight..g.[3] <- 1e+7
afrotheria.lifesize$Adult.weight..g.[4] <- 6e+6
afrotheria.lifesize$Adult.weight..g.[6] <- 5.5e+6
# Also see http://library.sandiegozoo.org/factsheets/_extinct/mammoth/mammoth.htm for more estimates

# Add in the color
afrotheria.lifesize %<>% 
  mutate(
    Col=sapply(
      id, 
      function(x, colscheme=afrotheria.colorScheme.species){
        colscheme[[x]]
        }
      )
    )

# Labeling the tree by clade
afrotreeria %<>% groupClade(., afrotheria.clades)

# Graphing
afrotreeria.phy <- afrotreeria %>% 
  ggtree(
    aes(color=factor(group))
) + 
    geom_tiplab(col="black") +
    scale_color_manual(
      # Ok a breakdown: groupClade assigns numbers to each clade based on the ORIGINAL order in afrotheria.clades,
      # so in the named vector for values, we need to assign colors to said numbers, NOT to the group names
        values=c(
            "0"="#1B9E77",
            "1"="#7570B3",
            "2"="#D95F02",
            "3"="#E7298A",
            "4"="#66A61E",
            "5"="#E6AB02",
            "6"="#A6761D",
            # Now, because I decided "hey let's add in the literal colors as a column," R will use that column as the 
            # KEYS for which to assign colors. In other words, now I need a named vector that has the colors assigned 
            # to themselves...
            "#A6761D" = "#A6761D",
            "#976C1B" = "#976C1B",
            "#886118" = "#886118",
            "#795616" = "#795616",
            "#5B4110" = "#5B4110",
            "#3D2B0B" = "#3D2B0B",
            "#E6AB02" = "#E6AB02",
            "#66A61E" = "#66A61E",
            "#E7298A" = "#E7298A",
            "#7570B3" = "#7570B3",
            "#605C93" = "#605C93",
            "#4B4872" = "#4B4872",
            "#D95F02" = "#D95F02",
            "#C65702" = "#C65702"),
        labels=c(
          # Leave out the colors' names, we don't need them
            "0"="Other",
            "1"="Afroinsectivora",
            "2"="Xenarthra",
            "3"="Pseudoungulata",
            "4"="Paenungulata",
            "5"="Tethytheria",
            "6"="Elephantidae"),
        limits=c(
          # Only define in limits the names of items from the color scale that we care about showing in the legend
          # In other words, only show the clade color scheme, but leave the color scheme for species unexplained.
          # Really the species-specific hues are for visual appeal, but its not essential for the understanding of 
          # the graphs, since the bar graphs are lined with with the species names.
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6"),
        name="Clades"
    ) +
    #geom_text2(aes(subset=!isTip, label=node), hjust=-.3) +
    xlim_tree(15)

afrotreeria.phy %<>% flip(tree_view = ., 26, 25) # Flip to have LoxAfr on top

afrotreeria.phy.lifespan <- facet_plot(
  p=afrotreeria.phy, 
  panel='Lifespan - log(yrs)', 
  data=afrotheria.lifesize, 
  geom=geom_segment, 
  aes(
    x=0, 
    xend=log10(`Maximum.longevity..yrs.`), 
    y=y, 
    yend=y,
    color=Col
    )
  ) 
afrotreeria.phy.lifespan.size <- facet_plot(
  p=afrotreeria.phy.lifespan, 
  panel='Adult Weight - log(g)', 
  data=afrotheria.lifesize, 
  geom=geom_segment, 
  aes(
    x=0, 
    xend=log10(`Adult.weight..g.`), 
    y=y, 
    yend=y,
    color=Col
    )
  )
afrotreeria.phy.lifespan.size + 
  theme_tree2() + 
  theme(
    legend.position="bottom",
    strip.background = element_rect(fill="#1B9E77"),
    strip.text = element_text(size = rel(1.5)),
    plot.background = element_rect(fill="black"),
    panel.border = element_blank(),
    axis.text.x = element_text(color="white", size=rel(1)),
    legend.background = element_rect(fill="black"),
    legend.text = element_text(color="white"),
    legend.title = element_text(color="white")
    ) +
  xlim_tree(30)
```

```{r genomes, eval=T}
genomes <- list(
  "loxAfr3",
  "triMan1",
  "proCap1", 
  "oryAfe1",
  "echTel2",
  "dasNov3"
  ) %>% set_names(.,.)
```

```{r, eval=T}
tt <- read_tsv("../../../RecBlast/output/recBlastDBPrep/UP000005640.withheader.filtered.tsv")
  
genomes %>%
  lapply(
    .,
    function(g){
      dir(path = str_glue("../../../RecBlast/output/{g}/AvA-pcScore0.1_pcIdent0.8_pcQuerySpan0.5/filtered/"), pattern=".*_rbb_evidenced\\.bed12", full.names = T) %>% 
      read_tsv(col_names = F, col_types = "cccccccccccc") %>% 
    separate(X4, c("X4","n"), sep="_") %>% 
    left_join(., tt %>% select(ID, Name) %>% unique %>% rename(X4=ID), by="X4") %>% 
    unite(X4, c("Name", "n"), sep = "_") %>% 
    select(X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12) %>% 
    write_tsv(str_glue("../../../RecBlast/output/{g}/AvA-pcScore0.1_pcIdent0.8_pcQuerySpan0.5/other/{g}_rbb_evidenced_GeneNames.bed12"), col_names = F)}
  )
```


```{r, eval=T}
rbbs <- genomes %>% 
  lapply(
    ., 
    function(g){
      dir(path = str_glue("../../../RecBlast/output/{g}/AvA-pcScore0.1_pcIdent0.8_pcQuerySpan0.5/other/"), pattern=".*_RBB_GeneNames_merged\\.bed12", full.names = T) %>% 
        read_tsv(., col_names = F, col_types = "ccccc") %>% 
        mutate(
          X4 = X4 %>% 
            str_remove_all("_[0-9]+") %>% 
            str_split(",") %>% 
            sapply(
              .,
              . %>% 
                unique %>% 
                str_flatten(",")
            )
        )
      }
  )
rbbs.overlaps <- rbbs %>% lapply(
  .,
  . %>% pull(X4) %>% .[!str_detect(.,",")]
)

rbbs.overlaps %>% 
  names %>% 
  lapply(
    .,
    function(x, rbb=rbbs.overlaps){
      rbb[[x]] %>% 
        unique %>% 
        write_lines(str_glue("../../../RecBlast/output/{x}/AvA-pcScore0.1_pcIdent0.8_pcQuerySpan0.5/other/{x}_merged_all.txt"))
      rbb[[x]] %>% 
        .[duplicated(.)] %>% 
        unique %>% 
        write_lines(str_glue("../../../RecBlast/output/{x}/AvA-pcScore0.1_pcIdent0.8_pcQuerySpan0.5/other/{x}_merged_dups.txt"))
    }
  )
```


```{r hit data, eval=T}
hit.dat <- genomes %>% 
  lapply(
    .,
    function(g){
      list(
        base::dir(path = paste("../../../RecBlast/output/", g, "/AvA-pcScore0.1_pcIdent0.8_pcQuerySpan0.5/other/genesymbol/", sep=""), pattern="_geneNames_all.txt", full.names = T) %>% read_lines(file=.),
        base::dir(path = paste("../../../RecBlast/output/", g, "/AvA-pcScore0.1_pcIdent0.8_pcQuerySpan0.5/other/genesymbol/", sep=""), pattern="_geneNames_dups.txt", full.names = T) %>% read_lines(file=.)
        ) %>% 
        set_names(c(str_glue("{g}_Hits"), str_glue("{g}_Duplicates")))
    }
  )
count.dat <- hit.dat %>% 
  lapply(
    .,
    function(g){
      lapply(
        g, 
        length
        )
    }
  ) %>% 
  unlist %>% 
  cbind %>% 
  as.data.frame %>% 
  rownames_to_column("g") %>% 
  rename(Count=".") %>% 
  separate(
    g, 
    c("id","Class"),
    sep="_"
  ) %>% 
  mutate(
    id=sapply(
      id,
      function(g){
        ifelse(
          g=="loxAfr3.loxAfr3",
          "L.africana\nloxAfr3",
          ifelse(
            g=="proCap1.proCap1",
            "P.capensis\nproCap1",
            ifelse(
              g=="triMan1.triMan1",
              "T.manatus\ntriMan1",
              ifelse(
                g=="oryAfe1.oryAfe1",
                "O.afer\noryAfe1",
                ifelse(
                  g=="echTel2.echTel2",
                  "E.telfairi\nechTel2",
                  ifelse(
                    g=="dasNov3.dasNov3",
                    "D.novemcinctus\ndasNov3",
                    NA
                  )
                )
              )
            )
          )
          )
      }
      )
  )

count.dat

```


```{r, eval=T}
genomes.searched <- read.newick("../../../RecBlast/data/tree/genomes.tree")
genomes.searched$tip.label <- gsub("\\\\n","\n", genomes.searched$tip.label)

afrotheria.colorScheme2 <- list(
  "#1B9E77",
  "Afroinsectivora"="#7570B3",
  "D.novemcinctus\\ndasNov3"="#7570B3",
  "Xenarthra"="#D95F02",
  "E.telfairi\\nechTel2"="#D95F02",
  "Pseudoungulata"="#E7298A",
  "O.afer\\noryAfe1"="#E7298A",
  "Paenungulata"="#66A61E",
  "P.capensis\\nproCap1"="#66A61E",
  "Tethytheria"="#E6AB02",
  "T.manatus\\ntriMan1"="#E6AB02",
  "L.africana\\nloxAfr3"="#A6761D"
)

b <- genomes.searched %>% 
  groupClade(., c(10,11,12,13,14)) %>% 
  ggtree(
    aes(
      color=factor(group)
      )
    ) +
  geom_tiplab(
    color="black",
    size=rel(5)
  )
b %<>% flip(tree_view = ., 1, 2)


b %>% 
  facet_plot(
    p=.,
    panel="Hits",
    data = count.dat,
    geom=geom_barh,
    mapping = aes(
      x = Count,
      fill = as.factor(Class)
    ),
    position=position_dodgev(height=1),
    stat="identity"
  ) %>% 
  facet_plot(
    p=.,
    panel="Hits",
    data = count.dat,
    geom=geom_text,
    mapping = aes(
      x = Count,
      group = as.factor(Class),
      label=as.character(Count)
    ),
    position=position_dodgev(height=1),
    hjust=-0.5,
    color="black",
    size=rel(5)
  ) +
theme_tree2() + 
  theme(
    legend.position="bottom",
    strip.background = element_rect(fill="#1B9E77"),
    strip.text = element_text(size = rel(1.5)),
    plot.background = element_rect(fill="black"),
    panel.border = element_blank(),
    axis.text.x = element_text(color="white", size=rel(1)),
    legend.background = element_rect(fill="black"),
    legend.text = element_text(color="white"),
    legend.title = element_text(color="white")
  ) +
  scale_color_manual(
    values=c(
      "0"="#1B9E77",
      "4"="#7570B3",
      "5"="#D95F02",
      "1"="#E7298A",
      "2"="#66A61E",
      "3"="#E6AB02"
    ),
    labels=c(
      "0"="Other",
      "4"="Afroinsectivora",
      "5"="Xenarthra",
      "1"="Pseudoungulata",
      "2"="Paenungulata",
      "3"="Tethytheria"),
    limits=c("0", "1", "2", "3", "4", "5"),
    name="Clades"
  ) +
  scale_fill_viridis(
    discrete = T,
    name="Count",
    label=c("Duplicated", "Singleton")
    )+
  xlim_tree(c(0,8))+
  xlim_expand(c(0, max(count.dat$Count)+5000), "Hits")

```


```{r, eval=T}
(ORAs <- c(genomes, "mm10") %>% 
  set_names(.,.) %>% 
    lapply(
      ., . %>% 
      {
        base::dir(
          path = str_glue("../../../RecBlast/output/{.}/AvA-pcScore0.1_pcIdent0.8_pcQuerySpan0.5/other/genesymbol/Project_{.}_AvA-pcScore0.1_pcIdent0.8_pcQuerySpan0.5_geneNames_dups"), 
          pattern="enrichment_results", 
          full.names = T
        ) %>% 
          read_tsv(.)}
      )
)
```

```{r, eval=T}
(interesting_hits <- tribble(
  ~Gene, ~Reactome.Pathway, ~Copies, ~TPMs,
  "PCNA", "Translesion syntheis by REV1", 2, "259.401672;0.085464",
  "RFC5", "Translesion syntheis by REV1", 2, "12.613674;0",
  "RPA2", "Translesion syntheis by REV1", 2, "7.924984;6.832592",
  "UBE2C", "Cellular response to stress", 4, "28.034910;72.136497;6.145966;0",
  "DNAJC2","Cellular response to stress", 2, "4.600700;0",
  "ATOX1", "Cellular response to stress", 2, "10.121429;0",
  "SOD1", "Cellular response to stress", 2, "113.214508;10.245503",
  "MAD2L1", "Mitotic Prometaphase", 7, "53.247437;46.728935;1.984854;53.247437;6.405835;37.413486;0"
) %>% 
  separate_rows(TPMs, sep=";") %>% 
  group_by(Gene) %>% 
  mutate(id=1:max(Copies)) %>% 
  ungroup %>% 
  mutate(
    Gene=as.factor(Gene),
    id=as.factor(id),
    TPMs=as.numeric(TPMs),
    Reactome.Pathway=as.factor(Reactome.Pathway)
  )
)

library(ggpubr)

(plot.ihits <- interesting_hits %>% 
    ggplot(
      aes(
        x=id, 
        y=TPMs, 
        color=Reactome.Pathway
        )
      ) +
    geom_point(
      size=3
    )+
    geom_segment(
      aes(
        x=id,
        xend=id,
        y=0,
        yend=TPMs
      )
    )+
    scale_y_sqrt()+
    scale_color_brewer(palette = "Dark2", name="Reactome Pathway", guide=guide_legend(nrow = 2))+
    theme_pubclean()+
    labs(
      x="Copy",
      y="TPM"
    )+
    facet_grid(~Gene, scales = "free")+ 
  theme(
    legend.position="bottom",
    strip.background = element_rect(fill="#1B9E77"),
    strip.text = element_text(size = rel(1.5)),
    plot.background = element_rect(fill="black"),
    panel.border = element_blank(),
    text = element_text(color="white"),
    axis.title = element_text(color="white", size=rel(1.5)),
    axis.text = element_text(color="white", size=rel(1)),
    legend.background = element_rect(fill="black"),
    legend.text = element_text(color="white"),
    legend.title = element_text(color="white", size=rel(1))
  )
)  
plot.ihits
```



